import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex flex-col justify-center items-between gap-[5vh] bg-gray-700'>
        <header className='bg-gray-200 h-[50px] flex gap-6 pt-4 pl-4'>
          <Link href="/">Form</Link>
          <Link href="/test">Details</Link>
        </header>
        {children}


      </body>
    </html>
  )
}
